### PR TITLE
make simple-rl an actual package

### PR DESCRIPTION
**Pull request by jsalvatier**
I had to move things into a directory called `simple_rl` in order for installation to work.

### CODE REVIEW

**Comment by jsalvatier** [comment]
Also I came across a problem: 

Any idea what this is about?

```(env) ➜  simple_rl git:(package) ✗ python run_experiments.py -mdp=taxi
Running experiment:
(MDP)
        taxi_h-2_w-2
(Agents)
        rmax-h4
        random
        lin_q_approx
(Params)
        num_instances : 10
        num_episodes : 20
        num_steps : 50

rmax-h4 is learning.
        Instance 0 of 10.
        Instance 1 of 10.
        Instance 2 of 10.
        Instance 3 of 10.
        Instance 4 of 10.
        Instance 5 of 10.
        Instance 6 of 10.
        Instance 7 of 10.
        Instance 8 of 10.
        Instance 9 of 10.
random is learning.
        Instance 0 of 10.
        Instance 1 of 10.
        Instance 2 of 10.
        Instance 3 of 10.
        Instance 4 of 10.
        Instance 5 of 10.
        Instance 6 of 10.
        Instance 7 of 10.
        Instance 8 of 10.
        Instance 9 of 10.
lin_q_approx is learning.
        Instance 0 of 10.
Traceback (most recent call last):
  File "run_experiments.py", line 175, in <module>
    main()
  File "run_experiments.py", line 171, in main
    run_agents_on_mdp([rmax_agent, random_agent, lin_approx_agent], mdp)
  File "run_experiments.py", line 70, in run_agents_on_mdp
    action = agent.act(state, reward)
  File "/Users/jsalvatier/workspace/ml/human-rl/simple_rl/simple_rl/agents/QLearnerAgentClass.py", line 55, in act
    action = self.epsilon_greedy_q_policy(state)
  File "/Users/jsalvatier/workspace/ml/human-rl/simple_rl/simple_rl/agents/QLearnerAgentClass.py", line 72, in epsilon_greedy_q_policy
    action = self.get_max_q_action(state)
  File "/Users/jsalvatier/workspace/ml/human-rl/simple_rl/simple_rl/agents/QLearnerAgentClass.py", line 145, in get_max_q_action
    return self._compute_max_qval_action_pair(state)[1]
  File "/Users/jsalvatier/workspace/ml/human-rl/simple_rl/simple_rl/agents/QLearnerAgentClass.py", line 130, in _compute_max_qval_action_pair
    q_s_a = self.get_q_value(state, action)
  File "/Users/jsalvatier/workspace/ml/human-rl/simple_rl/simple_rl/agents/LinearApproxQLearnerAgentClass.py", line 101, in get_q_value
    sa_feats = self._phi(state, action)
  File "/Users/jsalvatier/workspace/ml/human-rl/simple_rl/simple_rl/agents/LinearApproxQLearnerAgentClass.py", line 58, in _phi
    return numpy.array(blank_vec[:act_index*self.num_features] + list(state.features()) + blank_vec[(act_index)*self.num_features:])
ValueError: setting an array element with a sequence.
```

**Comment by jsalvatier** [comment]
@david-abel how did you get the graph that you put up during the meeting?

**Comment by david-abel** [comment]
@jsalvatier:

Re: the package business. Yeah that's a good call! I'm working on making things cooperate with pip and work out of the box via cloning.

Re: flattening state features --> Taxi should be using OOMDPStates which forms a flat feature list. You may have a slightly old version (after the meeting I pushed some more recent changes).

Re: the graph --> When the experiments finish, the plot will open. I think I ran things with: 10 instances, 100 episodes, 100 actions per episode.

**Comment by jsalvatier** [comment]
Great! That worked

**Pull request closed without merging**
